# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_firstname', models.CharField(max_length=15)),
                ('u_secondname', models.CharField(max_length=15)),
                ('u_firstlastname', models.CharField(max_length=15)),
                ('u_secondlastname', models.CharField(max_length=15)),
                ('u_password', models.CharField(max_length=20)),
                ('u_jobtitle', models.CharField(max_length=100)),
                ('u_department', models.CharField(max_length=100)),
                ('u_oficina', models.CharField(max_length=100)),
                ('u_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('u_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
