# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.User'),
        ),
    ]
