# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TicketsApp', '0003_auto_20160323_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_secondname', models.CharField(max_length=30)),
                ('u_secondlastname', models.CharField(max_length=30)),
                ('u_jobtitle', models.CharField(max_length=100)),
                ('u_department', models.CharField(max_length=100)),
                ('u_oficina', models.CharField(max_length=100)),
                ('u_createddate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_email',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='u_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
