# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0004_auto_20160323_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='u_oficina',
            new_name='u_office',
        ),
    ]
