# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0006_auto_20160331_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='d_management',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.Management'),
        ),
        migrations.AddField(
            model_name='management',
            name='m_company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.Company'),
        ),
    ]
