# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0008_auto_20160331_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='d_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='d_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
