# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0009_auto_20160404_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='u_id',
        ),
    ]
