# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TicketsApp', '0010_remove_userprofile_u_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('a_id', models.IntegerField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=100)),
                ('a_route', models.CharField(max_length=200)),
                ('a_description', models.CharField(max_length=1000)),
                ('a_dateattached', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AddField(
            model_name='archive',
            name='a_ticket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.Ticket'),
        ),
        migrations.AddField(
            model_name='archive',
            name='a_userattacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='a_userattacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
