# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 21:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TicketsApp', '0014_auto_20160406_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('at_id', models.IntegerField(primary_key=True, serialize=False)),
                ('at_tipe', models.CharField(max_length=100)),
                ('at_date', models.DateTimeField()),
                ('at_timeinverted', models.DateTimeField()),
                ('at_description', models.CharField(max_length=500)),
                ('at_createdby', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='at_createdby', to=settings.AUTH_USER_MODEL)),
                ('at_ticket', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.Ticket')),
            ],
        ),
    ]
