# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0015_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='a_route',
            field=models.FileField(upload_to=''),
        ),
    ]
