# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0016_auto_20160407_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='t_title',
            field=models.CharField(default='Titulo', max_length=100),
            preserve_default=False,
        ),
    ]
