# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 13:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0018_auto_20160411_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='at_timeinverted',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 9, 27, 6, 295133)),
        ),
        migrations.AlterField(
            model_name='archive',
            name='a_route',
            field=models.FileField(upload_to='MEDIA_URL'),
        ),
    ]
