# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 21:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0020_auto_20160413_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='at_timeinverted',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 13, 16, 36, 16, 53557)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_usersolver',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_usersolver', to=settings.AUTH_USER_MODEL),
        ),
    ]
