# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 18:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0021_auto_20160413_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_number', models.IntegerField()),
                ('s_measure', models.CharField(max_length=20)),
                ('s_delta', models.DurationField()),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='at_timeinverted',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 14, 24, 31, 683632)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_sla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla', to='TicketsApp.SLA'),
        ),
    ]
