# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0022_auto_20160414_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sla',
            name='s_delta',
        ),
        migrations.AlterField(
            model_name='activity',
            name='at_timeinverted',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 14, 27, 34, 395432)),
        ),
    ]
