# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0029_auto_20160427_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='at_timeinverted',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 3, 13, 35, 52, 633870)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_reportmadeon',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 3, 13, 35, 52, 631869)),
        ),
    ]
