# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 12:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0030_auto_20160503_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='c_incident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='c_requisite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='c_solicitude',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='at_timeinverted',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 12, 8, 53, 54, 92296)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_reportmadeon',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 12, 8, 53, 54, 89294)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.Server'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.Service'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
