# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0032_auto_20160512_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='at_timeinverted',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 12, 9, 48, 46, 319462)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_isincident',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_reportmadeon',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 12, 9, 48, 46, 316460)),
        ),
    ]
