# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0033_auto_20160512_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='at_timeinverted',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 12, 11, 6, 5, 429567)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_reportmadeon',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 12, 11, 6, 5, 427567)),
        ),
    ]
