# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 12:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TicketsApp', '0037_auto_20160516_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.Department')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='at_timeinverted',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 3, 8, 20, 0, 549890)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_reportmadeon',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 3, 8, 20, 0, 534258)),
        ),
        migrations.AddField(
            model_name='department',
            name='d_haveview',
            field=models.ManyToManyField(related_name='viewers', through='TicketsApp.Member', to=settings.AUTH_USER_MODEL),
        ),
    ]
