# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0043_auto_20160609_0906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actions',
            new_name='Action',
        ),
        migrations.RemoveField(
            model_name='state',
            name='s_last',
        ),
        migrations.RemoveField(
            model_name='state',
            name='s_next',
        ),
        migrations.AlterField(
            model_name='activity',
            name='at_timeinverted',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 9, 12, 53, 921673)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_reportmadeon',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 9, 12, 53, 919672)),
        ),
    ]
