# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0044_auto_20160609_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ty_name', models.CharField(max_length=100)),
                ('ty_color', models.CharField(max_length=20)),
                ('ty_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.Workflow')),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='at_timeinverted',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 9, 31, 45, 956404)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_isincident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.Type'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_reportmadeon',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 9, 31, 45, 954401)),
        ),
    ]
