# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 13:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0045_auto_20160609_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='t_isincident',
        ),
        migrations.AddField(
            model_name='ticket',
            name='t_ttype',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.Type'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='at_timeinverted',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 9, 36, 38, 970175)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_reportmadeon',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 9, 36, 38, 968176)),
        ),
    ]
