# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0046_auto_20160609_0936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Ttype',
        ),
        migrations.AlterField(
            model_name='activity',
            name='at_timeinverted',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 9, 38, 16, 419255)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_reportmadeon',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 9, 38, 16, 417254)),
        ),
    ]
