# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0047_auto_20160609_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ctype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='c_incident',
        ),
        migrations.RemoveField(
            model_name='company',
            name='c_requisite',
        ),
        migrations.RemoveField(
            model_name='company',
            name='c_solicitude',
        ),
        migrations.AddField(
            model_name='state',
            name='s_workflow',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.Workflow'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='at_timeinverted',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 11, 27, 52, 588782)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_reportmadeon',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 11, 27, 52, 586781)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.State'),
        ),
        migrations.AddField(
            model_name='ctype',
            name='ct_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.Company'),
        ),
        migrations.AddField(
            model_name='ctype',
            name='ct_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.Ttype'),
        ),
    ]
