# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0057_auto_20160609_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='at_timeinverted',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 14, 5, 28, 181949)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_reportmadeon',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 14, 5, 28, 166321)),
        ),
        migrations.AlterField(
            model_name='ttype',
            name='ty_icon',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
